version: "3"
services:
  microblog:
    image: microblog:1.1
    ports:
      - "8000:5000"
    volumes:
      - .:/home/microblog
    env_file:
      - .env
  db:
    image: mysql/mysql-server:5.7
    env_file:
      - .env
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file:
      - .env
